HTTP/1.1 200 OK
authenticated: false
cache-control: post-check=0, pre-check=0
content-length: 89
content-type: application/json; charset=utf-8
date: Mon, 30 Sep 2024 19:03:37 GMT
expires: Tue, 03 Jul 2001 06:00:00 GMT
last-modified: Mon Sep 30 2024 19:03:37 GMT+0000 (Coordinated Universal Time)
server: Google Frontend
strict-transport-security: max-age=15552000; includeSubDomains
vary: Origin
x-cloud-trace-context: 1cd07748e986593249b4e0e5a7fcb8b6
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-response-time: 1ms
x-xss-protection: 1; mode=block

[
  {
    "id": "59k",
    "url": "https://cdn2.thecatapi.com/images/59k.jpg",
    "width": 500,
    "height": 375
  }
]